#!/usr/bin/env python3
"""Builds plan.json: 200 question-led posts, 4 services x 7 cities, one per day.
{city} in a title is replaced with the assigned city; titles without it still get a city for schema/body angle."""
import json, re, datetime
CITIES = ["Seattle","Everett","Lynnwood","Kirkland","Edmonds","Sammamish","Snohomish"]
R = [  # hardwood refinishing
 "How Much Does It Cost to Refinish Hardwood Floors in {city}? (2026 Real Prices)",
 "Can My Hardwood Floors Be Refinished, or Do They Need Replacing? The {city} Homeowner's Checklist",
 "How Long Does Hardwood Floor Refinishing Take? Day-by-Day Timeline for {city} Homes",
 "Refinish or Recoat? How to Tell Which One Your Hardwood Floors Actually Need",
 "Is Dustless Hardwood Floor Refinishing Really Dustless? What {city} Homeowners Should Expect",
 "Water-Based vs Oil-Based Finish: What Holds Up Best on Hardwood Floors in the Pacific Northwest",
 "Can Engineered Hardwood Floors Be Refinished? Wear Layer Rules Explained",
 "How Many Times Can Hardwood Floors Be Refinished Before They're Done?",
 "Can Pet Urine Stains Be Sanded Out of Hardwood Floors? Honest Answers From {city} Jobs",
 "Do I Need to Move Out While My Hardwood Floors Are Refinished?",
 "Hardwood Floor Stain Colors Trending in {city} for 2026 (And Which Ones Age Badly)",
 "Can Red Oak Floors Be Stained to Look Like White Oak? What Works and What Doesn't",
 "Is It Worth Refinishing Hardwood Floors Before Selling a House in {city}?",
 "How Soon Can You Walk on Refinished Hardwood Floors and Move Furniture Back?",
 "Why Are My Hardwood Floors Turning Gray or Black? Causes and the Fix",
 "Can Water-Damaged Hardwood Floors Be Refinished? When Sanding Works and When It Doesn't",
 "Screening vs Buffing vs Sanding Hardwood Floors: What Each One Actually Does",
 "What's Under My Carpet? Refinishing the Hardwood Hiding in {city} Homes",
 "How to Refinish Old Fir Floors in a 1920s {city} House Without Ruining Them",
 "Should You Refinish Hardwood Floors Before or After Painting and Remodeling?",
 "Can Hardwood Floors Be Refinished in Winter? Refinishing During {city}'s Rainy Season",
 "What Does a 500 Sq Ft Minimum Mean for Refinishing One Room?",
 "Can I Refinish Just One Room of Hardwood? Will It Match the Rest of the House?",
 "Matte vs Satin vs Semi-Gloss: Which Sheen Is Right for Refinished Hardwood Floors?",
 "How to Fix Scratches in Hardwood Floors Without a Full Refinish",
 "Are Refinished Hardwood Floors Safe for Babies and Pets? VOCs, Cure Times and Bona Finishes",
 "How to Prepare Your {city} Home for Hardwood Floor Refinishing: The Complete Checklist",
 "How Much Does It Cost to Refinish Hardwood Stairs in {city}?",
 "Can Parquet Floors Be Refinished? What Changes With the Pattern",
 "Can Gaps in Hardwood Floors Be Fixed During Refinishing?",
 "Why Does My Refinished Floor Look Blotchy? 7 Contractor Mistakes to Avoid in {city}",
 "What Does Bona Certified Craftsman Mean, and Why Does It Matter for Your Floors?",
 "DIY Hardwood Floor Refinishing vs Hiring a Pro in {city}: The Real Cost Comparison",
 "Can You Change the Color of Hardwood Floors Without Sanding?",
 "How to Clean and Maintain Refinished Hardwood Floors So They Last 20 Years",
 "Refinishing Hardwood Floors in {city} Condos: Rules, Noise, Elevators and Timing",
 "Does Refinishing Hardwood Floors Increase Home Value in {city}? ROI Numbers",
 "Can Refinishing Fix Squeaky Hardwood Floors?",
 "Can Sun-Faded Hardwood Floors Under Rugs Be Fixed?",
 "How to Refinish Hardwood Floors With a Dog in the House",
 "Can Bamboo Floors Be Refinished? What Most {city} Homeowners Get Wrong",
 "Cupped or Crowned Hardwood Floors: Can They Be Sanded Flat?",
 "How to Get a Light Scandinavian Look on Red Oak Floors in {city}",
 "Old Wax or Oil Finish on Hardwood Floors: How It Gets Removed Before Refinishing",
 "Can Painted Hardwood Floors Be Refinished Back to Natural Wood?",
 "How to Compare Hardwood Refinishing Quotes in {city}: What a Real Quote Must Include",
 "When Is the Best Time of Year to Refinish Hardwood Floors in {city}?",
 "Refinish the Old Hardwood or Cover It With Vinyl Plank? The Smarter Choice for {city} Homes",
 "How Thick Does Hardwood Need to Be to Refinish? Measuring Your Wear Layer",
 "What Is the Most Durable Finish for Hardwood Floors With Kids and Dogs?",
]
H = [  # hardwood installation
 "How Much Does Hardwood Floor Installation Cost in {city}? 2026 Labor and Material Prices",
 "Engineered vs Solid Hardwood: Which Is Better for {city}'s Damp Climate?",
 "Can Hardwood Floors Be Installed Over a Concrete Slab?",
 "Can You Put Hardwood Floors in a Kitchen, Bathroom or Basement?",
 "What Is the Best Hardwood Flooring for Dogs? Species, Finish and Hardness Compared",
 "White Oak vs Red Oak Flooring: Which Should You Install in {city}?",
 "How Long Does Hardwood Floor Installation Take? A Realistic Timeline",
 "Nail-Down vs Glue-Down vs Floating Hardwood: Which Installation Method Is Right?",
 "Do Hardwood Floors Need to Acclimate Before Installation? How Long in {city}?",
 "Prefinished vs Site-Finished Hardwood Floors: Cost, Look and Durability",
 "Wide Plank vs Narrow Plank Hardwood: Pros, Cons and What Works in {city} Homes",
 "Can Hardwood Be Installed Over Existing Hardwood, Tile or Vinyl?",
 "Hardwood vs Luxury Vinyl Plank for Resale Value in {city}",
 "Which Direction Should Hardwood Floors Run? Layout Rules That Matter",
 "How Much Does Herringbone or Chevron Hardwood Flooring Cost to Install?",
 "How Much Does It Cost to Install Hardwood on Stairs in {city}?",
 "Can You Install Hardwood Floors Over Radiant Heat?",
 "Hickory vs Maple vs Oak Flooring: Durability, Janka Ratings and Price",
 "How Much Extra Hardwood Flooring Should You Order? Waste Factor Explained",
 "Do You Need Underlayment Under Hardwood Floors?",
 "What Subfloor Prep Is Needed Before Installing Hardwood Floors?",
 "Should You Install Hardwood Floors Yourself? DIY vs Pro Cost in {city}",
 "Hardwood Floors in {city} Condos and Second Floors: Sound Rules and Underlayment",
 "How to Match New Hardwood Floors to Existing Floors in an Older {city} Home",
 "How to Choose a Hardwood Floor Color for Dark Pacific Northwest Winters",
 "Can Hardwood Floors Be Installed in Winter? Humidity and Timing in {city}",
 "What's Included in a Hardwood Installation Quote? Labor vs Material Explained",
 "How a Mobile Flooring Showroom Works: Picking Hardwood in Your Own {city} Living Room",
 "Hardwood Floor Transitions and Thresholds: How Pros Handle Doorways and Tile",
 "Hardwood Over a Crawlspace: Vapor Barriers and Moisture Rules for {city} Homes",
 "Are Engineered Hardwood Floors Real Hardwood? What You're Actually Buying",
 "How Thick Should an Engineered Hardwood Wear Layer Be?",
 "What Is the Best Hardwood Flooring for High-Traffic Areas?",
 "How Much Does It Cost to Remove Old Carpet or Flooring Before Hardwood Installation?",
 "Baseboards and Quarter Round: What Happens to Trim During Hardwood Installation?",
 "Hardwood Floors in a New Build vs a Remodel: What Changes in {city}",
 "How Long After Hardwood Installation Can You Walk on It and Move Furniture?",
 "Hardwood vs Laminate Flooring: Which Is Worth It in {city}?",
 "Expansion Gaps in Hardwood Floors: Why Open Floor Plans Need Them",
 "Eco-Friendly Hardwood Flooring Options for {city} Homes: FSC, Low-VOC and Reclaimed",
 "What Does a Hardwood Floor Warranty Actually Cover?",
 "Is Hardwood Flooring Worth It in {city} Rental Properties?",
 "How to Prevent Scratches on New Hardwood Floors",
 "How to Choose Hardwood Flooring From Samples: A Method That Works",
 "Why Maple Floors Are Hard to Stain (And What to Do Instead)",
 "Hand-Scraped, Wire-Brushed or Smooth Hardwood: Which Texture Hides Wear Best?",
 "Best Flooring for Mudrooms and Entryways in Rainy {city}",
 "Do Hardwood Floors Increase Home Value in {city}? What Appraisers and Buyers Say",
 "How Far Out Should You Book Hardwood Installation in {city}? Lead Times Explained",
 "Hardwood Floor Installation in {city}: 5 Questions to Ask Before You Sign",
]
L = [  # vinyl plank
 "How Much Does Vinyl Plank Flooring Installation Cost in {city}? 2026 Prices",
 "LVP vs Laminate: Which Is Better for {city} Homes?",
 "Luxury Vinyl Plank vs Hardwood: Honest Pros and Cons for {city} Homeowners",
 "Is Vinyl Plank Flooring Really Waterproof? Basements, Bathrooms and Leaks",
 "Can Vinyl Plank Be Installed Over Tile, Hardwood, Concrete or Old Vinyl?",
 "SPC vs WPC Vinyl Plank: Which Core Is Right for Your Home?",
 "How Thick Should Vinyl Plank Flooring Be? Wear Layer Mils Explained",
 "What Is the Best Vinyl Plank Flooring for Dogs?",
 "Does Vinyl Plank Flooring Scratch? What Actually Damages LVP",
 "Does Vinyl Plank Flooring Look Cheap? Resale Value in {city}",
 "Click-Lock vs Glue-Down Vinyl Plank: Which Installation Is Better?",
 "Do You Need Underlayment Under Vinyl Plank Flooring?",
 "Can You Put Vinyl Plank in Bathrooms, Kitchens and Laundry Rooms?",
 "How Much Does Vinyl Plank on Stairs Cost in {city}?",
 "Does Vinyl Plank Flooring Need to Acclimate Before Installation?",
 "Why Is My Vinyl Plank Floor Buckling or Gapping? Expansion Gaps Explained",
 "How Long Does Vinyl Plank Installation Take? Room-by-Room Timeline",
 "Should You Install Vinyl Plank Yourself? DIY vs Pro Cost in {city}",
 "Best Flooring for {city} Rental Properties: Why Landlords Choose Vinyl Plank",
 "Is Vinyl Plank Flooring Toxic? VOCs, Phthalates and Certifications",
 "Can Vinyl Plank Flooring Be Repaired? Replacing a Single Damaged Plank",
 "Can Vinyl Plank Go Over Radiant Floor Heat?",
 "What to Look for in Vinyl Plank Flooring: Specs That Matter More Than Brand",
 "Why Vinyl Plank Floors Lift and Peak: Installation Mistakes We Fix in {city}",
 "How Flat Does a Subfloor Need to Be for Vinyl Plank?",
 "Vinyl Plank in {city} Condos: Sound Ratings, HOA Rules and Underlayment",
 "Vinyl Plank Over Uneven Floors and Crawlspaces in Older {city} Homes",
 "Vinyl Plank vs Tile in Bathrooms: Cost, Comfort and Durability",
 "Which Direction Should Vinyl Plank Flooring Run?",
 "Herringbone Vinyl Plank: Cost and What to Know Before You Order",
 "Vinyl Plank in Sunrooms and South-Facing Rooms: Heat, Fading and Expansion",
 "How Much Does It Cost to Replace Carpet With Vinyl Plank in {city}?",
 "Whole-House Vinyl Plank Installation in {city}: A Real Cost Example",
 "How to Clean Vinyl Plank Floors (And What Will Ruin Them)",
 "Do You Have to Remove Baseboards to Install Vinyl Plank?",
 "Rigid Core vs Flexible Vinyl Plank: Which One Do You Actually Want?",
 "Is Vinyl Plank a Good Choice for {city}'s Wet Climate?",
 "Best Flooring for Garage Conversions, ADUs and DADUs in {city}",
 "Cheap vs Premium Vinyl Plank: What You Actually Get for the Money",
 "Vinyl Plank in Kitchens: Heavy Appliances, Fridges and Dents",
 "Vinyl Plank vs Engineered Hardwood for Resale in {city}",
 "Does Vinyl Plank Need a Moisture Test Over Concrete?",
 "Vinyl Plank vs Sheet Vinyl vs Vinyl Tile: What's the Difference?",
 "Do Rolling Chairs and Heavy Furniture Dent Vinyl Plank?",
 "What's Included in a Vinyl Plank Installation Quote in {city}?",
 "Transition Strips From Vinyl Plank to Tile, Carpet and Hardwood",
 "Best Vinyl Plank for Rentals With Pets in {city}",
 "Vinyl Plank Flooring Trends for 2026: Widths, Colors and Patterns",
 "Can Vinyl Plank Be Installed in Winter in {city}?",
 "Vinyl Plank Installation in {city}: 7 Questions to Ask Your Installer",
]
C = [  # carpet
 "How Much Does Carpet Installation Cost in {city}? What Drives the Price in 2026",
 "Carpet vs Vinyl Plank for Bedrooms: Which Is Right for {city} Homes?",
 "What Is the Best Carpet for Pets? Fibers, Backing and Padding Compared",
 "What Is the Best Carpet for Stairs? Durability, Safety and Style",
 "How Long Does Carpet Last? When to Replace Carpet in {city} Homes",
 "Carpet Padding Explained: Thickness, Density and Why It Matters More Than the Carpet",
 "Nylon vs Polyester vs Triexta vs Wool Carpet: Which Fiber Should You Buy?",
 "Can You Put Carpet in a Basement in {city}? Moisture Rules First",
 "How Much Does It Cost to Carpet Stairs in {city}?",
 "How Long Does Carpet Installation Take? A Room-by-Room Timeline",
 "Should You Replace Carpet Before Selling a House in {city}?",
 "Best Carpet for Rental Properties in {city}: Cost vs Durability",
 "Berber vs Plush vs Frieze Carpet: Which Style Fits Your Home?",
 "Low-VOC Carpet: Does New Carpet Smell Go Away and Is It Safe?",
 "Is Carpet Bad for Allergies? What the Research Actually Says",
 "Can Carpet Be Installed Over Existing Carpet, Hardwood or Concrete?",
 "How to Prepare for Carpet Installation: Furniture, Doors and Old Carpet",
 "Carpet Seams: Where They Go and How to Keep Them Invisible",
 "Stretch-In vs Glue-Down Carpet: Which Installation Is Right?",
 "Best Carpet for Kids' Rooms and Playrooms in {city}",
 "Carpet Tiles vs Wall-to-Wall Carpet: Cost and Practicality",
 "What Is the Best Carpet for High-Traffic Areas?",
 "Light vs Dark Carpet: How to Choose a Color That Hides Wear",
 "How to Measure for Carpet: Rolls, Seams and Waste Factor Explained",
 "Best Carpet for a Home Office: Comfort, Chairs and Sound",
 "Carpet for Media Rooms and Basements: Soundproofing Benefits in {city} Homes",
 "Carpet vs Hardwood for Resale Value in {city}",
 "Wall-to-Wall Carpet vs Area Rug Over Hardwood: Which Makes Sense?",
 "Can Carpet Be Installed Over a Squeaky Subfloor?",
 "Is Wool Carpet Worth the Price? Pros and Cons for {city} Homes",
 "Carpet Pile Height and Your Vacuum: What Works Together",
 "Why Carpet Buckles and Ripples (And When Re-Stretching Beats Replacing)",
 "Patterned Carpet Trends for 2026: What Designers in {city} Are Choosing",
 "Can You Install Carpet Over Radiant Floor Heat?",
 "Carpet Removal and Disposal: What It Costs and What's Included in {city}",
 "Does Stain-Resistant Carpet Actually Work?",
 "What Does a Carpet Warranty Actually Cover?",
 "Best Carpet for Stairs With Dogs: Traction, Wear and Cleanup",
 "Carpet in {city} Condos: Sound Requirements and HOA Rules",
 "Is Carpet Outdated in 2026? Where It Still Wins",
 "Carpet to Hardwood Transitions: How Pros Finish the Edge",
 "Carpet Cushion vs Carpet Pad: Are They the Same Thing?",
 "Best Flooring for a Basement Remodel or ADU in {city}: Carpet, Vinyl or Both?",
 "How to Choose Carpet From Samples at Home: The Mobile Showroom Method",
 "Hypoallergenic Carpet: What's Real and What's Marketing",
 "How Far Out Should You Book Carpet Installation in {city}? Lead Times Explained",
 "Whole-House Carpet Installation in {city}: A Real Cost Example",
 "Can Carpet Be Installed in Winter in {city}? Humidity and Stretching",
 "Which Rooms Should Have Carpet? A Room-by-Room Guide for {city} Homes",
 "Cheap vs Quality Carpet: What You Actually Get for the Money",
]
assert len(R)==len(H)==len(L)==len(C)==50, (len(R),len(H),len(L),len(C))
STOP={"a","an","the","and","or","of","for","in","to","with","is","are","do","does","it","your","what","which","that","on","at","by","from","vs"}
def slugify(title, city):
    core=re.split(r"[?:(]", title)[0]
    t=core.lower().replace("&","and").replace("'","").replace("\u2019","")
    t=re.sub(r"[^a-z0-9]+","-",t).strip("-")
    if city.lower() not in t: t+="-"+city.lower()
    while len(t)>72 and "-" in t: t=t.rsplit("-",1)[0]
    parts=t.split("-")
    while parts and parts[-1] in STOP: parts.pop()
    return "-".join(parts)
plan=[]; start=datetime.date(2026,9,17)
banks=[("refinish",R,0),("hardwood",H,2),("lvp",L,4),("carpet",C,6)]
day=0
for i in range(50):
    for cat,bank,off in banks:
        city=CITIES[(i+off)%7]; title=bank[i].replace("{city}",city)
        slug=slugify(title, city)
        if "{city}" not in bank[i] and cat in ("refinish","hardwood","lvp","carpet"): pass
        plan.append({"n":len(plan)+1,"cat":cat,"city":city,"city_in_title":"{city}" in bank[i],"title":title,"slug":slug,"date":(start+datetime.timedelta(days=day)).isoformat()+"T15:00:00.000Z"})
        day+=1
slugs=[p["slug"] for p in plan]; assert len(set(slugs))==200, [s for s in slugs if slugs.count(s)>1]
json.dump(plan,open(__file__.replace("plan.py","plan.json"),"w"),indent=1)
print(len(plan),"posts,",plan[0]["date"][:10],"to",plan[-1]["date"][:10])
for p in plan[:8]: print(p["n"],p["cat"],p["city"],p["date"][:10],"|",p["title"],"|",p["slug"])
